# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojoname', models.CharField(max_length=255)),
                ('dojocity', models.TextField()),
                ('dojostate', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ninjas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninja_firstname', models.CharField(max_length=255)),
                ('ninja_lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
